package cn.easyproject.easyee.sm.cmsmoudle.criteria;

import cn.easyproject.easyee.sm.base.pagination.EasyCriteria;
import cn.easyproject.easyee.sm.base.util.StringUtils;


/**
 * Slider Criteria, generated by EasyAuto
 * @author easyproject.cn
 * @version 1.0
 *
 */
public class SliderCriteria extends EasyCriteria implements java.io.Serializable {
	// Fields
	private static final long serialVersionUID = 1L;
	/*
 	 * 1. Criteria property
 	 */
	/*
 	 * 2. Constructor
 	 */
	 public SliderCriteria() {
		super();
	}



	/*
 	 * 3. 条件生成抽象方法实现
 	 */
	@Override
	public String getCondition() {
		values.clear(); //清除条件数据
		StringBuffer condition = new StringBuffer();
		
		// Your conditions
		
		/*
		if (StringUtils.isNotNullAndEmpty(this.getName())) {
			condition.append(" and name like #{name}");
			values.put("name", "%" + this.getName() + "%");
		}
		*/
		
		
		return condition.toString();
	}
	
	 /*
 	 * 4. Setters & Getters...
 	 */ 


}