<!--${ClassName} Edit Page, generated by EasyAuto -->
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<%@ taglib uri="/struts-tags" prefix="s"%>

<%--  JavaScript  --%>


<script type="text/javascript">
$(function() {
	/*
	 * CRUD
	 */
	//Create or Update
	<#if editMutilpart>
		${ClassName}.edit = function() {
			var dg=$("#${ClassName}DataGrid");
			$("${ClassName}EditDialogPageSize").val(dg.datagrid("options").pageSize);
			
			$('#${ClassName}EditForm').form('submit', {
				 onSubmit:function(){
	                  return $(this).form('enableValidation').form('validate');
	            },
			    success: function(data){
			        var data = eval('(' + data + ')');  // change the JSON string to javascript object
			        if (data.statusCode==200) {
			        	dg.datagrid({"pageNumber":data.page});//Refresh datagrid
			        	uiEx.msg(data.msg);
						uiEx.closeDialog("#${ClassName}EditDialog");
					} else{
						uiEx.msg(data.msg);
					}
			    }
			});
		}
	<#else>
	${ClassName}.edit = function() {
		var dg=$("#${ClassName}DataGrid");
		var url = "${ClassName}/update";
		uiEx.submitURLAjax("#${ClassName}EditForm", url, function(data) {
			data = eval("(" + data + ")");
			// Refresh datagrid
			if (data.statusCode==200) {
				//uiEx.reloadSelTab("#tabs"); // Refresh Tab
				//dg.datagrid('reload'); //Refresh datagrid, Stay on the current page
				//dg.datagrid('load'); //Refresh datagrid
				dg.datagrid({"pageNumber":data.page});//Refresh datagrid
				uiEx.closeDialog("#${ClassName}EditDialog");
			} 
		},{"rows":dg.datagrid("options").pageSize});
	}
	</#if>
});

</script>

<%-- 2. Dialog --%>
<div id="${ClassName}EditDialog" class="easyui-dialog" style="width:480px;height:330px;padding:10px 20px;" resizable="true" closed="true" buttons="#${ClassName}Edit-dlg-buttons">
	<div class="ftitle">${ClsLabel}<s:text name="label.info"></s:text></div>
	<form id="${ClassName}EditForm" method="post" data-options="novalidate:true" <#if editMutilpart>enctype="multipart/form-data" action="${ClassName}/update"</#if>>
			<input name="${ClassName?uncap_first}.${Oid}" type="hidden">
			<#if editMutilpart><input name="rows" id="${ClassName}EditDialogPageSize" type="hidden"/></#if>
			 <table cellpadding="5">
			 	<#if Autos??>
				<#list Autos as item>
				<#assign info=item?split("#")>
				<#if info[5]=="true">
				<tr>
	    			<td>${info[2]}:</td>
	    			<td><input <#if info[6]=="false">readonly</#if> class="${info[7]} easyui-validatebox" name="${ClassName?uncap_first}.${info[1]}" <#if info[3]=="true">required="true"</#if> data-options="prompt:'input ${info[2]}...'"><#if info[3]=="true"><span class="required">*</span></#if></td>
	    		</tr>
				</#if>
				</#list>
				</#if>
	    	</table>
	</form>
</div>
<div id="${ClassName}Edit-dlg-buttons">
	<a class="easyui-linkbutton" id="${ClassName}EditSaveBtn" iconCls="icon-ok" onclick="${ClassName}.edit()"><s:text name="label.edit"></s:text></a> 
	<a class="easyui-linkbutton" iconCls="icon-cancel" onclick="javascript:uiEx.closeDialog('#${ClassName}EditDialog')"><s:text name="label.cancel"></s:text></a>
</div>