<!--Slider Edit Page, generated by EasyAuto -->
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>

<%-- 1. 页面Datagrid初始化相关JS --%>
<%-- JS代码必须包含在页面中，引入外部JS文件会导致表格界面在未完成初始化前就显示，出现短暂的未初始化界面 --%>

<script type="text/javascript">
$(function() {
	/*
	 * 执行增改
	 */
	//执行添加或修改
	Slider.edit = function() {
		var dg=$("#SliderDataGrid");
		var url = "Slider/update";
		uiEx.submitURLAjax("#SliderEditForm", url, function(data) {
			data = eval("(" + data + ")");
			// 执行成功，刷新dg
			if (data.statusCode==200) {
				//uiEx.reloadSelTab("#tabs"); // 刷新 Tab
				//dg.datagrid('reload'); //刷新表格，在当前页
				//dg.datagrid('load'); //刷新表格
				dg.datagrid({"pageNumber":data.page});//刷新表格
				uiEx.closeDialog("#SliderEditDialog");
			} 
		},{"rows":dg.datagrid("options").pageSize});
	}
});

</script>

<%-- 2. 添加或修改Dialog --%>
<div id="SliderEditDialog" class="easyui-dialog" style="width:480px;height:330px;padding:10px 20px;" resizable="true" closed="true" buttons="#SliderEdit-dlg-buttons">
	<div class="ftitle">首页轮播图片信息</div>
	<form id="SliderEditForm" method="post" data-options="novalidate:true" >
			<input name="id" type="hidden">
			
			 <table cellpadding="5">
				<tr>
	    			<td>图片:</td>
	    			<td><input readonly class="easyui-filebox easyui-validatebox" name="url"  data-options="prompt:'请输入图片...'"></td>
	    		</tr>
				<tr>
	    			<td>排序序号（由大到小）:</td>
	    			<td><input  class="numberbox easyui-validatebox" name="sort"  data-options="prompt:'请输入排序序号（由大到小）...'"></td>
	    		</tr>
	    	</table>
	</form>
</div>
<div id="SliderEdit-dlg-buttons">
	<a class="easyui-linkbutton" id="SliderEditSaveBtn" iconCls="icon-ok" onclick="Slider.edit()">修改</a> 
	<a class="easyui-linkbutton" iconCls="icon-cancel" onclick="javascript:uiEx.closeDialog('#SliderEditDialog')">取消</a>
</div>