<!--Slider Add Page, generated by EasyAuto -->
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>

<%-- 1. 页面Datagrid初始化相关JS --%>
<%-- JS代码必须包含在页面中，引入外部JS文件会导致表格界面在未完成初始化前就显示，出现短暂的未初始化界面 --%>
<script type="text/javascript">
$(function() {
	/*
	 * 执行增改
	 */
	//执行添加或修改
		Slider.add = function() {
			var dg=$("#SliderDataGrid");
			$("SliderAddDialogPageSize").val(dg.datagrid("options").pageSize);
			$('#SliderAddForm').form('submit', {
				 onSubmit:function(){
	                  return $(this).form('enableValidation').form('validate');
	            },
			    success: function(data){
			        var data = eval('(' + data + ')');  // change the JSON string to javascript object
			        if (data.statusCode==200) {
			        	dg.datagrid({"pageNumber":data.page});//刷新表格
			        	uiEx.msg(data.msg);
						uiEx.closeDialog("#SliderAddDialog");
					} else{
						uiEx.msg(data.msg);
					}
			    }
			});
		}
});


</script>

<%-- 2. 添加或修改Dialog --%>
<div id="SliderAddDialog" class="easyui-dialog" style="width:480px;height:330px;padding:10px 20px;" resizable="true" closed="true" buttons="#SliderAdd-dlg-buttons">
	<div class="ftitle">首页轮播图片信息</div>
	<form id="SliderAddForm" method="post" data-options="novalidate:true" enctype="multipart/form-data" action="Slider/save">
			<input name="id" type="hidden"/>
			<input name="rows" id="SliderAddDialogPageSize" type="hidden"/>
			 <table cellpadding="5">
				<tr>
	    			<td>图片:</td>
	    			<td><input class="easyui-filebox easyui-validatebox" name="url"  data-options="prompt:'请输入图片...'"></td>
	    		</tr>
				<tr>
	    			<td>排序序号（由大到小）:</td>
	    			<td><input class="numberbox easyui-validatebox" name="sort"  data-options="prompt:'请输入排序序号（由大到小）...'"></td>
	    		</tr>
	    	</table>
	</form>
</div>
<div id="SliderAdd-dlg-buttons">
	<a class="easyui-linkbutton" id="SliderAddSaveBtn" iconCls="icon-ok" onclick="Slider.add()">添加</a> 
	<a class="easyui-linkbutton" iconCls="icon-cancel" onclick="javascript:uiEx.closeDialog('#SliderAddDialog')">取消</a>
</div>