<!--Menu Form Page, generated by EasyAuto -->
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<%
	String path = request.getContextPath();
	String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort() + path + "/";
%>
<%@ taglib uri="http://shiro.apache.org/tags" prefix="shiro"%>

<script type="text/javascript">
	var Menu = {};
	$(function() {
		Menu.load=function(){
			$.post("Menu/list", {page:1,rows:1}, function(data){
				 uiEx.loadForm('#MenuDataForm', data.rows[0]);
			})
		}
		Menu.load();
		
		Menu.update=function(){
			uiEx.submitURLAjax("#MenuDataForm", "Menu/update", function(data) {
				if (data.statusCode==200) {
					uiEx.msg(data.msg);
				} else{
					uiEx.msg('修改失败！');
				}
			});
		} 
		
	});
</script>
<style>
.th{ font-weight: bold;padding-left: 35px}
</style>
<%-- 2. Form --%>
 <div class="easyui-panel" title="网站菜单" >
        <form id="MenuDataForm" style="width: 100%" method="post" >
       		<input name="id" type="hidden">
            <table cellpadding="5">
	    		 <tr>
                    <td class="th">菜单1:</td>
                    <td><input name="m1"  style="height: 30px;width: 350px" class="easyui-textbox" ></input></td>
                </tr>
	    		 <tr>
                    <td class="th">菜单2:</td>
                    <td><input name="m2"  style="height: 30px;width: 350px" class="easyui-textbox" ></input></td>
                </tr>
	    		 <tr>
                    <td class="th">菜单3:</td>
                    <td><input name="m3"  style="height: 30px;width: 350px" class="easyui-textbox" ></input></td>
                </tr>
	    		 <tr>
                    <td class="th">菜单4:</td>
                    <td><input name="m4"  style="height: 30px;width: 350px" class="easyui-textbox" ></input></td>
                </tr>
	    		 <tr>
                    <td class="th">菜单5:</td>
                    <td><input name="m5"  style="height: 30px;width: 350px" class="easyui-textbox" ></input></td>
                </tr>
	    		 <tr>
                    <td class="th">菜单6:</td>
                    <td><input name="m6"  style="height: 30px;width: 350px" class="easyui-textbox" ></input></td>
                </tr>
	    		 <tr>
                    <td class="th">菜单7:</td>
                    <td><input name="m7"  style="height: 30px;width: 350px" class="easyui-textbox" ></input></td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                    <a class="easyui-linkbutton" style="padding:3px 8px" id="MenuUpdateBtn" iconCls="icon-ok" onclick="Menu.update()">修改</a> 
					<a class="easyui-linkbutton" style="padding:3px 8px" iconCls="icon-cancel" onclick="Menu.load()">重置</a>
                    </td>
                </tr>
            </table>
        </form>
    </div>

<%-- 
<%@ include file="/WEB-INF/content/dialog/cmsmoudle/MenuAdd.jsp"%>  
<%@ include file="/WEB-INF/content/dialog/cmsmoudle/MenuEdit.jsp"%>  
--%>