<!--Slider Page, generated by EasyAuto -->
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<%
	String path = request.getContextPath();
	String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort() + path + "/";
%>
<%@ taglib uri="http://shiro.apache.org/tags" prefix="shiro"%>

<%-- 1. 页面Datagrid初始化相关JS --%>
<%-- JS代码必须包含在页面中，引入外部JS文件会导致表格界面在未完成初始化前就显示，出现短暂的未初始化界面 --%>
<script type="text/javascript">
	// Slider命名空间
	var Slider = {};
	$(function() {
		/*
		 * datagrid
		 */
		var dg = $("#SliderDataGrid");

		// EasyUIEx datagrid
		$("#SliderDataGrid").initDatagrid({
			/*
			 * CRUD URL
			 */
			url : "Slider/list",
			saveUrl : "Slider/save",
			updateUrl : "Slider/update",
			destroyUrl : "Slider/deleteBatch",
			
			idField : "id", // 主键列
			
			showHeaderContextMenu : true, // 表头添加右键菜单，可选择显示的列
			
			pagination : true, // 分页
			// pageSize: 10,
			// pageList: [10, 20, 30, 40, 50],
			
			//queryParams:{"rows":dg.datagrid("options").pageSize}, // 分页查询请求参数
			
			checkbox : true,
			checkOnSelect : true,
			singleSelect : false,
			
			// clickEdit : true, //单击编辑, EasyUI默认为双击
			// autoSave : true, // 自动保存
			
			showMsg : true, // 显示操作消息
			
			menuSelector : "#SliderContextMenu", //右键菜单
			showContextMenu : true,
			
			sendRowDataPrefix : "", //提交数据前缀
			
			successKey : "statusCode", //服务器端返回的成功标记key
			successValue : "200", //服务器端返回的成功标记value
			
			onLoadSuccess : function(data) {
			},
			
			//双击操作
			onDblClickRow : function(rowIndex, rowData) {
				toEdit(rowData);
			}
			
			,mutipleDelete : true, // 多行提交删除
			mutipleDeleteProperty : "id" // 多行删除时提及给服务器的属性和值，不会添加sendRowDataPrefix前缀，支持使用数组指定多个属性名
		});

		/*
		 * Functions
		 */
		// 搜索
		Slider.doSearch = function() {
			dg.datagrid("load", {
			});
		}
		
		// 清除所有搜索条件
		Slider.clearAll = function() {
			$("#SliderSearchForm")[0].reset();
			dg.datagrid("load", {
			});
		}
		
		// 删除
		Slider.toDelete = function() {
			var rows = $("#SliderDataGrid").datagrid('getSelections');
			if (rows) {
				dg.rowDelete(true, false, "statusCode", "200");
			} else {
				uiEx.msg("请选择要删除的行");
			}
		}
		
		// 添加
		Slider.toAdd = function() {
			uiEx.resetForm("#SliderAddForm");
			uiEx.openDialog("#SliderAddDialog", "首页轮播图片添加");
		}
		
		//点击按钮修改
		Slider.toEdit = function() {
			var row = $("#SliderDataGrid").datagrid('getSelected');
			if (row) {
				toEdit(row);
			} else {
				uiEx.msg("请选择要修改的行");
			}
		}
		//打开修改	
		function toEdit(row) {
			uiEx.resetForm("#SliderEditForm");
			uiEx.openDialog("#SliderEditDialog", "首页轮播图片修改");

			uiEx.loadForm("#SliderEditForm", row, "");
		}

	});
</script>


<%-- 2. 页面内容  DataGrid --%>
<table id="SliderDataGrid" title="首页轮播图片列表" style="width: 100%" toolbar="#SliderToolbar" idField="id" rownumbers="true" fitColumns="true" nowrap="false">
	<thead>
		<tr>
			<th field="ck" checkbox="true" width="50" sortable="true">多选框</th>
			<th field="url" width="50" sortable="true">图片</th>
			<th field="sort" width="50" sortable="true">排序序号（由大到小）</th>
		</tr>
	</thead>
</table>

<%-- 3. 搜索条件部分  Toolbar --%>
<div id="SliderToolbar">
	<div>
	<form action="" id="SliderSearchForm" onsubmit="Slider.doSearch();return false">
		<a class="easyui-linkbutton" iconCls="icon-search" plain="true" onclick="Slider.doSearch()">Search</a>
		<a class="easyui-linkbutton" iconCls="icon-clear" plain="true" onclick="Slider.clearAll()">Clear</a>
		<input type="submit" style="display: none;"/>
	</form>
	</div>
	<a href="javascript:void(0)" class="easyui-linkbutton" data-options="iconCls:'icon-add',plain:true" onclick="Slider.toAdd()">添加首页轮播图片</a>
	<a href="javascript:void(0)" class="easyui-linkbutton" data-options="iconCls:'icon-edit',plain:true" onclick="Slider.toEdit()">修改首页轮播图片</a>
	<a class="easyui-linkbutton" iconCls="icon-remove" plain="true" onclick="Slider.toDelete()">删除首页轮播图片</a>
</div>

<%-- 4. grid右键菜单 --%>
<div id="SliderContextMenu" class="easyui-menu" style="width:120px;">
	<div onclick="Slider.toAdd()" data-options="iconCls:'icon-add'">添加首页轮播图片</div>
	<div onclick="Slider.toEdit()" data-options="iconCls:'icon-edit'">修改首页轮播图片</div>
	<div onclick="Slider.toDelete()" data-options="iconCls:'icon-remove'">删除首页轮播图片</div>
</div>

<%-- 5. 包含的Dialog页面等其他内容 --%>
<%@ include file="/WEB-INF/content/dialog/cmsmoudle/SliderAdd.jsp"%>
<%@ include file="/WEB-INF/content/dialog/cmsmoudle/SliderEdit.jsp"%>
